// REPOSITORY TYPES
export const FETCH_USERS = "FETCH_USERS"
export const FETCH_REPOSITORIES = "FETCH_REPOSITORIES"
export const FETCH_REPOSITORY_CONTRIBUTORS = "FETCH_REPOSITORY_CONTRIBUTORS"
export const FETCH_REPOSITORY = "FETCH_REPOSITORY"

// TRACKS TYPE
export const FETCH_TRACKS_REPOSITORIES = "FETCH_TRACKS_REPOSITORIES"
export const FETCH_TRACKS_USERS = "FETCH_TRACKS_USERS"
export const SAVE_REPOSITORY = "SAVE_REPOSITORY"
export const SAVE_USER = "SAVE_USER"

// ERROR AND LOADING TYPES
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const LOADING_DATA = "LOADING_DATA"
export const LOADING_AUTH_DATA = "LOADING_AUTH_DATA"
export const CLEAR_LOADING_DATA = "CLEAR_LOADING_DATA"
