// REPOSITORY TYPES
export const FETCH_USERS = "FETCH_USERS"
export const FETCH_REPOSITORIES = "FETCH_REPOSITORIES"
export const FETCH_REPOSITORY = "FETCH_REPOSITORY"

// ERROR AND LOADING TYPES
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const LOADING_DATA = "LOADING_DATA"
export const LOADING_AUTH_DATA = "LOADING_AUTH_DATA"
export const CLEAR_LOADING_DATA = "CLEAR_LOADING_DATA"
